#!/usr/bin/env node
/**
 * Run the mouse-driven mobile layout spec under WebKit.
 *
 * Playwright refuses `--browser=webkit` whenever the config defines projects,
 * so the engine has to be swapped through a config file. This writes a
 * throwaway one, runs it, and always removes it again.
 *
 * The temp config lands at the REPO ROOT on purpose: spreading baseConfig
 * carries `testDir: "./apps/e2e"` as a relative string, which Playwright
 * re-resolves against whichever directory the config file sits in. Written
 * anywhere else, it would resolve to a directory that does not exist.
 *
 * Only `browserName` is overridden. Keeping viewport, touch, and the webServer
 * identical to the chromium project means a failure here is an engine
 * difference and nothing else.
 *
 * Usage: node .claude/skills/webkit-check/scripts/webkit-check.mjs [playwright flags]
 */
import { writeFileSync, rmSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(SCRIPT_DIR, "../../../..");

// apps/e2e/mobile/ is CDP-locked (newCDPSession is Chromium-only) and cannot
// run here. See the SKILL.md section on why that is settled, not a gap.
const SPEC = "apps/e2e/mobile-layout.spec.ts";
const CONFIG_NAME = "playwright.webkit-check.tmp.config.ts";
const CONFIG_PATH = path.join(REPO, CONFIG_NAME);

const CONFIG_SOURCE = `// Generated by .claude/skills/webkit-check — deleted automatically.
// Edits here are lost on every run; change the skill's script instead.
import { defineConfig } from "@playwright/test";
import baseConfig from "./playwright.config";

export default defineConfig({
  ...baseConfig,
  projects: [
    {
      name: "mobile-webkit",
      use: { ...baseConfig.use, browserName: "webkit" },
      testIgnore: /[\\\\/]mobile[\\\\/]/,
    },
  ],
});
`;

function cleanup() {
  // force: a missing file is the normal case on the SIGINT path when the run
  // already cleaned up, and should not turn an interrupt into an error.
  rmSync(CONFIG_PATH, { force: true });
}

if (existsSync(CONFIG_PATH)) {
  // Left behind by a hard kill (SIGKILL skips both handlers below). Safe to
  // replace: nothing but this script ever writes that filename.
  console.warn(`[webkit-check] replacing stale ${CONFIG_NAME}`);
}

process.on("SIGINT", () => {
  cleanup();
  process.exit(130);
});

let status = 1;
try {
  writeFileSync(CONFIG_PATH, CONFIG_SOURCE);
  const result = spawnSync(
    "pnpm",
    ["exec", "playwright", "test", `--config=${CONFIG_NAME}`, SPEC, ...process.argv.slice(2)],
    { cwd: REPO, stdio: "inherit", shell: true },
  );
  status = result.status ?? 1;
} finally {
  cleanup();
}

if (status === 0) {
  console.log(
    "\n[webkit-check] WebKit renders the mobile shell. Note this is not iOS Safari —\n" +
      "no address-bar resize, safe-area insets, or real touch. Those need a real device.",
  );
}
process.exit(status);
