// GENERATED FILE — do not edit by hand. Regenerate with:
//   node scripts/import-monster-library.mjs
// Source pack: HeroByte Pixel 15 Monster Library (184 tokens, manifest created 2026-09-15T01:56:41.839851+00:00).
//
// One entry per line on purpose (prettier-ignore): the 350-line structure
// guard counts lines, and a pretty-printed object per token would be seven
// lines each. The image for an entry is monsterImageUrl(entry).

import type { MonsterAsset, MonsterFamily } from "./monsterCatalogTypes";

/** Families in the pack's roadmap order — the order the library lists them. */
// prettier-ignore
export const MONSTER_FAMILIES: readonly MonsterFamily[] = [
  { id: "Goblins", label: "Goblins" },
  { id: "Skeletons", label: "Skeletons" },
  { id: "Bandits", label: "Bandits" },
  { id: "Zombies", label: "Zombies" },
  { id: "Wolves", label: "Wolves" },
  { id: "Orcs", label: "Orcs" },
  { id: "Kobolds", label: "Kobolds" },
  { id: "Spiders", label: "Spiders" },
  { id: "Cultists", label: "Cultists" },
  { id: "Ghouls", label: "Ghouls" },
  { id: "Gnolls", label: "Gnolls" },
  { id: "Ogres", label: "Ogres" },
  { id: "Worgs", label: "Worgs" },
  { id: "Mephits", label: "Mephits" },
  { id: "FlyingPests", label: "Flying Pests" },
  { id: "Blights", label: "Blights" },
  { id: "Lizardfolk", label: "Lizardfolk" },
  { id: "Constructs", label: "Constructs" },
  { id: "Rats", label: "Rats" },
  { id: "Harpies", label: "Harpies" },
  { id: "Owlbears", label: "Owlbears" },
  { id: "Hags", label: "Hags" },
  { id: "Demons", label: "Demons" },
  { id: "Devils", label: "Devils" },
  { id: "Trolls", label: "Trolls" },
  { id: "Elementals", label: "Elementals" },
  { id: "Ettercaps", label: "Ettercaps" },
  { id: "Mummies", label: "Mummies" },
  { id: "Gargoyles", label: "Gargoyles" },
  { id: "Mimics", label: "Mimics" },
];

/** Every token in the pack, grouped by family. */
// prettier-ignore
export const MONSTER_ASSETS: readonly MonsterAsset[] = [
  { id: "goblinClub", family: "Goblins", title: "Club brute", name: "Goblin club brute" },
  { id: "goblinCommander", family: "Goblins", title: "Commander", name: "Goblin commander" },
  { id: "goblinMage", family: "Goblins", title: "Mage", name: "Goblin mage" },
  { id: "goblinUnarmedScavanger", family: "Goblins", title: "Scavenger", name: "Goblin scavenger" },
  { id: "goblinScimatar", family: "Goblins", title: "Scimitar fighter", name: "Goblin scimitar fighter" },
  { id: "goblinShortBow", family: "Goblins", title: "Shortbow archer", name: "Goblin shortbow archer" },
  { id: "goblinSling", family: "Goblins", title: "Slinger", name: "Goblin slinger" },
  { id: "goblinSpear", family: "Goblins", title: "Spear fighter", name: "Goblin spear fighter" },
  { id: "goblinSwordShield", family: "Goblins", title: "Sword & shield guard", name: "Goblin sword & shield guard" },
  { id: "goblinTrapper", family: "Goblins", title: "Trapper", name: "Goblin trapper" },
  { id: "goblinWargRider", family: "Goblins", title: "Warg rider", name: "Goblin warg rider" },
  { id: "skeletonBrute", family: "Skeletons", title: "Brute", name: "Skeleton brute" },
  { id: "skeletonChampion", family: "Skeletons", title: "Champion", name: "Skeleton champion" },
  { id: "skeletonMage", family: "Skeletons", title: "Mage", name: "Skeleton mage" },
  { id: "skeletonRustySword-proportions-v3", family: "Skeletons", title: "Rusty sword fighter", name: "Skeleton rusty sword fighter" },
  { id: "skeletonScavenger", family: "Skeletons", title: "Scavenger", name: "Skeleton scavenger" },
  { id: "skeletonShieldGuard", family: "Skeletons", title: "Shield guard", name: "Skeleton shield guard" },
  { id: "skeletonShortbow", family: "Skeletons", title: "Shortbow archer", name: "Skeleton shortbow archer" },
  { id: "skeletonSpear", family: "Skeletons", title: "Spear fighter", name: "Skeleton spear fighter" },
  { id: "banditArcher", family: "Bandits", title: "Archer", name: "Bandit archer" },
  { id: "banditCaptain", family: "Bandits", title: "Captain", name: "Bandit captain" },
  { id: "banditBrute", family: "Bandits", title: "Club brute", name: "Bandit club brute" },
  { id: "banditSapper", family: "Bandits", title: "Sapper", name: "Bandit sapper" },
  { id: "banditScout", family: "Bandits", title: "Scout", name: "Bandit scout" },
  { id: "banditShield", family: "Bandits", title: "Shield bruiser", name: "Bandit shield bruiser" },
  { id: "banditSpear", family: "Bandits", title: "Spear fighter", name: "Bandit spear fighter" },
  { id: "banditSwordsman", family: "Bandits", title: "Swordsman", name: "Bandit swordsman" },
  { id: "zombieBloated", family: "Zombies", title: "Bloated zombie", name: "Bloated zombie" },
  { id: "zombieNoble", family: "Zombies", title: "Buried noble", name: "Zombie buried noble" },
  { id: "zombieCrawler", family: "Zombies", title: "Crawler", name: "Zombie crawler" },
  { id: "zombieGuard", family: "Zombies", title: "Fallen guard", name: "Zombie fallen guard" },
  { id: "zombieLaborer", family: "Zombies", title: "Laborer", name: "Zombie laborer" },
  { id: "zombieShambler", family: "Zombies", title: "Shambler", name: "Zombie shambler" },
  { id: "wolfDire", family: "Wolves", title: "Dire wolf", name: "Dire wolf" },
  { id: "wolfGray", family: "Wolves", title: "Gray wolf", name: "Gray wolf" },
  { id: "wolfTimber", family: "Wolves", title: "Timber wolf", name: "Timber wolf" },
  { id: "wolfWinter", family: "Wolves", title: "Winter wolf", name: "Winter wolf" },
  { id: "orcArcher", family: "Orcs", title: "Archer", name: "Orc archer" },
  { id: "orcAxe", family: "Orcs", title: "Axe raider", name: "Orc axe raider" },
  { id: "orcBrute", family: "Orcs", title: "Hammer brute", name: "Orc hammer brute" },
  { id: "orcScout", family: "Orcs", title: "Scout", name: "Orc scout" },
  { id: "orcShaman", family: "Orcs", title: "Shaman", name: "Orc shaman" },
  { id: "orcShieldGuard", family: "Orcs", title: "Shield guard", name: "Orc shield guard" },
  { id: "orcSpear", family: "Orcs", title: "Spear fighter", name: "Orc spear fighter" },
  { id: "orcWarlord", family: "Orcs", title: "Warlord", name: "Orc warlord" },
  { id: "koboldChieftain", family: "Kobolds", title: "Chieftain", name: "Kobold chieftain" },
  { id: "koboldDagger", family: "Kobolds", title: "Dagger skirmisher", name: "Kobold dagger skirmisher" },
  { id: "koboldHeavyPick", family: "Kobolds", title: "Heavy miner", name: "Kobold heavy miner" },
  { id: "koboldShaman", family: "Kobolds", title: "Shaman", name: "Kobold shaman" },
  { id: "koboldShieldGuard", family: "Kobolds", title: "Shield guard", name: "Kobold shield guard" },
  { id: "koboldSling", family: "Kobolds", title: "Slinger", name: "Kobold slinger" },
  { id: "koboldSpear", family: "Kobolds", title: "Spear fighter", name: "Kobold spear fighter" },
  { id: "koboldTrapper", family: "Kobolds", title: "Trapper", name: "Kobold trapper" },
  { id: "spiderCave", family: "Spiders", title: "Cave spider", name: "Cave spider" },
  { id: "spiderBlack", family: "Spiders", title: "Giant black spider", name: "Giant black spider" },
  { id: "spiderBrown", family: "Spiders", title: "Giant brown spider", name: "Giant brown spider" },
  { id: "spiderWebmother", family: "Spiders", title: "Web mother", name: "Spider web mother" },
  { id: "cultistAcolyte", family: "Cultists", title: "Acolyte", name: "Cultist acolyte" },
  { id: "cultistArcher", family: "Cultists", title: "Cult archer", name: "Cult archer" },
  { id: "cultistGuard", family: "Cultists", title: "Cult guard", name: "Cult guard" },
  { id: "cultistLeader", family: "Cultists", title: "Cult leader", name: "Cult leader" },
  { id: "cultistRelicBearer", family: "Cultists", title: "Relic bearer", name: "Cultist relic bearer" },
  { id: "cultistRitualist", family: "Cultists", title: "Ritualist", name: "Cultist ritualist" },
  { id: "cultistSummoner", family: "Cultists", title: "Summoner", name: "Cultist summoner" },
  { id: "cultistZealot", family: "Cultists", title: "Zealot", name: "Cultist zealot" },
  { id: "ghoulArmored", family: "Ghouls", title: "Armored ghoul", name: "Armored ghoul" },
  { id: "ghoulScavenger", family: "Ghouls", title: "Crypt scavenger", name: "Ghoul crypt scavenger" },
  { id: "ghastChampion", family: "Ghouls", title: "Ghast champion", name: "Ghast champion" },
  { id: "ghoulBrute", family: "Ghouls", title: "Ghoul brute", name: "Ghoul brute" },
  { id: "ghoulLeaper", family: "Ghouls", title: "Ghoul leaper", name: "Ghoul leaper" },
  { id: "ghoulStalker", family: "Ghouls", title: "Ghoul stalker", name: "Ghoul stalker" },
  { id: "gnollArcher", family: "Gnolls", title: "Archer", name: "Gnoll archer" },
  { id: "gnollAxe", family: "Gnolls", title: "Axe raider", name: "Gnoll axe raider" },
  { id: "gnollBrute", family: "Gnolls", title: "Bone-club brute", name: "Gnoll bone-club brute" },
  { id: "gnollPacklord", family: "Gnolls", title: "Packlord", name: "Gnoll packlord" },
  { id: "gnollScavenger", family: "Gnolls", title: "Scavenger", name: "Gnoll scavenger" },
  { id: "gnollShaman", family: "Gnolls", title: "Shaman", name: "Gnoll shaman" },
  { id: "gnollShield", family: "Gnolls", title: "Shield guard", name: "Gnoll shield guard" },
  { id: "gnollSpear", family: "Gnolls", title: "Spear hunter", name: "Gnoll spear hunter" },
  { id: "ogreArmored", family: "Ogres", title: "Armored ogre", name: "Armored ogre" },
  { id: "ogreClub", family: "Ogres", title: "Club ogre", name: "Club ogre" },
  { id: "ogreChieftain", family: "Ogres", title: "Ogre chieftain", name: "Ogre chieftain" },
  { id: "ogreHurler", family: "Ogres", title: "Stone hurler", name: "Ogre stone hurler" },
  { id: "worgScarred", family: "Worgs", title: "Scarred worg", name: "Scarred worg" },
  { id: "worgStandard", family: "Worgs", title: "Worg", name: "Worg" },
  { id: "worgAlpha", family: "Worgs", title: "Worg alpha", name: "Worg alpha" },
  { id: "mephitDust", family: "Mephits", title: "Dust mephit", name: "Dust mephit" },
  { id: "mephitIce", family: "Mephits", title: "Ice mephit", name: "Ice mephit" },
  { id: "mephitMagma", family: "Mephits", title: "Magma mephit", name: "Magma mephit" },
  { id: "mephitMud", family: "Mephits", title: "Mud mephit", name: "Mud mephit" },
  { id: "mephitSmoke", family: "Mephits", title: "Smoke mephit", name: "Smoke mephit" },
  { id: "mephitSteam", family: "Mephits", title: "Steam mephit", name: "Steam mephit" },
  { id: "stirgeBloated", family: "FlyingPests", title: "Bloated stirge", name: "Bloated stirge" },
  { id: "stirgePale", family: "FlyingPests", title: "Cave stirge", name: "Cave stirge" },
  { id: "batDire", family: "FlyingPests", title: "Dire bat", name: "Dire bat" },
  { id: "batGiant", family: "FlyingPests", title: "Giant bat", name: "Giant bat" },
  { id: "stirgeStandard", family: "FlyingPests", title: "Stirge", name: "Stirge" },
  { id: "blightAncient", family: "Blights", title: "Ancient blight", name: "Ancient blight" },
  { id: "blightBloom", family: "Blights", title: "Corrupted bloom", name: "Blight corrupted bloom" },
  { id: "blightNeedle", family: "Blights", title: "Needle blight", name: "Needle blight" },
  { id: "blightThorn", family: "Blights", title: "Thorn blight", name: "Thorn blight" },
  { id: "blightTwig", family: "Blights", title: "Twig blight", name: "Twig blight" },
  { id: "blightVine", family: "Blights", title: "Vine blight", name: "Vine blight" },
  { id: "lizardfolkArcher", family: "Lizardfolk", title: "Archer", name: "Lizardfolk archer" },
  { id: "lizardfolkChieftain", family: "Lizardfolk", title: "Chieftain", name: "Lizardfolk chieftain" },
  { id: "lizardfolkClub", family: "Lizardfolk", title: "Club warrior", name: "Lizardfolk club warrior" },
  { id: "lizardfolkScout", family: "Lizardfolk", title: "Marsh scout", name: "Lizardfolk marsh scout" },
  { id: "lizardfolkTrapper", family: "Lizardfolk", title: "Net trapper", name: "Lizardfolk net trapper" },
  { id: "lizardfolkBrute", family: "Lizardfolk", title: "Shell-maul brute", name: "Lizardfolk shell-maul brute" },
  { id: "lizardfolkShield", family: "Lizardfolk", title: "Shield guard", name: "Lizardfolk shield guard" },
  { id: "lizardfolkSpear", family: "Lizardfolk", title: "Spear hunter", name: "Lizardfolk spear hunter" },
  { id: "lizardfolkShaman", family: "Lizardfolk", title: "Swamp shaman", name: "Lizardfolk swamp shaman" },
  { id: "lizardfolkMatriarch", family: "Lizardfolk", title: "War matriarch", name: "Lizardfolk war matriarch" },
  { id: "animatedArmor", family: "Constructs", title: "Animated armor", name: "Animated armor" },
  { id: "flyingAxe", family: "Constructs", title: "Flying axe", name: "Flying axe" },
  { id: "flyingHalberd", family: "Constructs", title: "Flying halberd", name: "Flying halberd" },
  { id: "flyingSword", family: "Constructs", title: "Flying sword", name: "Flying sword" },
  { id: "animatedArmorGuard", family: "Constructs", title: "Haunted shield guard", name: "Haunted shield guard" },
  { id: "animatedArmorChampion", family: "Constructs", title: "Runic armor champion", name: "Runic armor champion" },
  { id: "ratAlbino", family: "Rats", title: "Albino rat", name: "Albino rat" },
  { id: "ratBrown", family: "Rats", title: "Giant brown rat", name: "Giant brown rat" },
  { id: "ratSwarm", family: "Rats", title: "Rat swarm", name: "Rat swarm" },
  { id: "ratSewer", family: "Rats", title: "Sewer rat", name: "Sewer rat" },
  { id: "harpyCliff", family: "Harpies", title: "Cliff harpy", name: "Cliff harpy" },
  { id: "harpyMatriarch", family: "Harpies", title: "Harpy matriarch", name: "Harpy matriarch" },
  { id: "harpySea", family: "Harpies", title: "Sea harpy", name: "Sea harpy" },
  { id: "harpyStorm", family: "Harpies", title: "Storm harpy", name: "Storm harpy" },
  { id: "owlbearJuvenile", family: "Owlbears", title: "Juvenile owlbear", name: "Juvenile owlbear" },
  { id: "owlbearStandard", family: "Owlbears", title: "Owlbear", name: "Owlbear" },
  { id: "owlbearAlpha", family: "Owlbears", title: "Scarred alpha", name: "Owlbear scarred alpha" },
  { id: "owlbearSnow", family: "Owlbears", title: "Snowy owlbear", name: "Snowy owlbear" },
  { id: "hagBogOracle", family: "Hags", title: "Bog oracle", name: "Hag bog oracle" },
  { id: "hagCovenMatriarch", family: "Hags", title: "Coven matriarch", name: "Hag coven matriarch" },
  { id: "hagGreen", family: "Hags", title: "Green hag", name: "Green hag" },
  { id: "hagNight", family: "Hags", title: "Night hag", name: "Night hag" },
  { id: "hagSea", family: "Hags", title: "Sea hag", name: "Sea hag" },
  { id: "demonAbyssalMage", family: "Demons", title: "Abyssal hexer", name: "Demon abyssal hexer" },
  { id: "demonBrute", family: "Demons", title: "Bloated brute", name: "Demon bloated brute" },
  { id: "demonHorned", family: "Demons", title: "Horned warrior", name: "Demon horned warrior" },
  { id: "demonClawed", family: "Demons", title: "Lesser clawed demon", name: "Lesser clawed demon" },
  { id: "demonSpined", family: "Demons", title: "Spined demon", name: "Spined demon" },
  { id: "demonWinged", family: "Demons", title: "Winged scout", name: "Demon winged scout" },
  { id: "devilChainWarden", family: "Devils", title: "Chain warden", name: "Devil chain warden" },
  { id: "devilHornedExecutioner", family: "Devils", title: "Horned executioner", name: "Devil horned executioner" },
  { id: "devilImp", family: "Devils", title: "Imp scout", name: "Imp scout" },
  { id: "devilCaster", family: "Devils", title: "Infernal caster", name: "Infernal caster" },
  { id: "devilCommander", family: "Devils", title: "Infernal commander", name: "Infernal commander" },
  { id: "devilSoldier", family: "Devils", title: "Infernal soldier", name: "Infernal soldier" },
  { id: "trollCommon", family: "Trolls", title: "Forest troll", name: "Forest troll" },
  { id: "trollRegrown", family: "Trolls", title: "Scarred troll", name: "Scarred troll" },
  { id: "trollSwamp", family: "Trolls", title: "Swamp troll", name: "Swamp troll" },
  { id: "trollBrute", family: "Trolls", title: "Troll brute", name: "Troll brute" },
  { id: "elementalAir", family: "Elementals", title: "Air elemental", name: "Air elemental" },
  { id: "elementalEarthCrystal", family: "Elementals", title: "Crystal earth elemental", name: "Crystal earth elemental" },
  { id: "elementalEarth", family: "Elementals", title: "Earth elemental", name: "Earth elemental" },
  { id: "elementalFire", family: "Elementals", title: "Fire elemental", name: "Fire elemental" },
  { id: "elementalFireGreater", family: "Elementals", title: "Greater fire elemental", name: "Greater fire elemental" },
  { id: "elementalWater", family: "Elementals", title: "Water elemental", name: "Water elemental" },
  { id: "ettercapBrute", family: "Ettercaps", title: "Brood brute", name: "Ettercap brood brute" },
  { id: "ettercapBroodkeeper", family: "Ettercaps", title: "Brood keeper", name: "Ettercap brood keeper" },
  { id: "ettercapStalker", family: "Ettercaps", title: "Cave stalker", name: "Ettercap cave stalker" },
  { id: "ettercapHunter", family: "Ettercaps", title: "Web hunter", name: "Ettercap web hunter" },
  { id: "ettercapTrapper", family: "Ettercaps", title: "Web trapper", name: "Ettercap web trapper" },
  { id: "mummyArmored", family: "Mummies", title: "Armored mummy", name: "Armored mummy" },
  { id: "mummyShield", family: "Mummies", title: "Burial shield guard", name: "Mummy burial shield guard" },
  { id: "mummyPriest", family: "Mummies", title: "Mummy priest", name: "Mummy priest" },
  { id: "mummySovereign", family: "Mummies", title: "Mummy sovereign", name: "Mummy sovereign" },
  { id: "mummySpear", family: "Mummies", title: "Tomb spear guard", name: "Mummy tomb spear guard" },
  { id: "mummyWanderer", family: "Mummies", title: "Tomb wanderer", name: "Mummy tomb wanderer" },
  { id: "gargoyleChampion", family: "Gargoyles", title: "Gargoyle champion", name: "Gargoyle champion" },
  { id: "gargoyleHorned", family: "Gargoyles", title: "Horned gargoyle", name: "Horned gargoyle" },
  { id: "gargoyleMarble", family: "Gargoyles", title: "Marble watcher", name: "Gargoyle marble watcher" },
  { id: "gargoyleMoss", family: "Gargoyles", title: "Mossy gargoyle", name: "Mossy gargoyle" },
  { id: "gargoyleSentinel", family: "Gargoyles", title: "Stone sentinel", name: "Gargoyle stone sentinel" },
  { id: "mimicBarrelHidden", family: "Mimics", title: "Closed barrel", name: "Closed barrel", mimic: "disguised", counterpartId: "mimicBarrel" },
  { id: "mimicBarrel", family: "Mimics", title: "Barrel mimic", name: "Barrel mimic", mimic: "revealed", counterpartId: "mimicBarrelHidden" },
  { id: "mimicChestHidden", family: "Mimics", title: "Closed chest", name: "Closed chest", mimic: "disguised", counterpartId: "mimicChest" },
  { id: "mimicChest", family: "Mimics", title: "Chest mimic", name: "Chest mimic", mimic: "revealed", counterpartId: "mimicChestHidden" },
  { id: "mimicDoorHidden", family: "Mimics", title: "Closed dungeon door", name: "Closed dungeon door", mimic: "disguised", counterpartId: "mimicDoor" },
  { id: "mimicDoor", family: "Mimics", title: "Door mimic", name: "Door mimic", mimic: "revealed", counterpartId: "mimicDoorHidden" },
  { id: "mimicSarcophagusHidden", family: "Mimics", title: "Closed sarcophagus", name: "Closed sarcophagus", mimic: "disguised", counterpartId: "mimicSarcophagus" },
  { id: "mimicSarcophagus", family: "Mimics", title: "Sarcophagus mimic", name: "Sarcophagus mimic", mimic: "revealed", counterpartId: "mimicSarcophagusHidden" },
  { id: "mimicBookHidden", family: "Mimics", title: "Closed spellbook", name: "Closed spellbook", mimic: "disguised", counterpartId: "mimicBook" },
  { id: "mimicBook", family: "Mimics", title: "Spellbook mimic", name: "Spellbook mimic", mimic: "revealed", counterpartId: "mimicBookHidden" },
];
