// Tileset v1 atlas: one baked sheet + UV manifest (apps/client/public/tiles,
// regenerated by scripts/build-tile-atlas.ps1). Loaded lazily as a static
// asset — never part of the JS bundle — and shared by every render surface
// (editor underlay today, the live table in R5). Families absent from the
// manifest (water, uploads) keep their flat fills.
import { useEffect, useState } from "react";

export interface TileAtlasVariant {
  col: number;
  row: number;
}

export interface TileAtlasManifest {
  version: number;
  image: string;
  tileSize: number;
  columns: number;
  families: Record<string, { variants: TileAtlasVariant[]; averageColor?: string }>;
}

export interface TileAtlasRect {
  x: number;
  y: number;
  size: number;
}

export interface TileAtlas {
  image: CanvasImageSource;
  tileForCell(assetId: string, cellX: number, cellY: number): TileAtlasRect | null;
}

/**
 * Deterministic spatial hash: the same cell always picks the same variant,
 * so painted maps look varied but stable across redraws, sessions, and
 * clients. Math.imul keeps 32-bit semantics for negative cell indices.
 */
export function variantIndexForCell(cellX: number, cellY: number, count: number): number {
  if (count <= 1) return 0;
  const hash = (Math.imul(cellX, 73856093) ^ Math.imul(cellY, 19349663)) >>> 0;
  return hash % count;
}

export function createTileAtlas(manifest: TileAtlasManifest, image: CanvasImageSource): TileAtlas {
  return {
    image,
    tileForCell(assetId, cellX, cellY) {
      const family = manifest.families[assetId];
      if (!family || family.variants.length === 0) return null;
      const variant = family.variants[variantIndexForCell(cellX, cellY, family.variants.length)]!;
      return {
        x: variant.col * manifest.tileSize,
        y: variant.row * manifest.tileSize,
        size: manifest.tileSize,
      };
    },
  };
}

const TILESET_MANIFEST_URL = "/tiles/tileset-v1.json";

let atlasPromise: Promise<TileAtlas | null> | null = null;

/**
 * Load the bundled tileset once per session. Resolves null on any failure
 * (offline, missing files) — consumers fall back to flat fills, never throw.
 */
export function loadTileAtlas(): Promise<TileAtlas | null> {
  atlasPromise ??= fetchTileAtlas();
  return atlasPromise;
}

async function fetchTileAtlas(): Promise<TileAtlas | null> {
  try {
    const response = await fetch(TILESET_MANIFEST_URL);
    if (!response.ok) return null;
    const manifest = (await response.json()) as TileAtlasManifest;
    const image = await loadAtlasImage(`/tiles/${manifest.image}`);
    return createTileAtlas(manifest, image);
  } catch {
    return null;
  }
}

function loadAtlasImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error("Unable to load tile atlas image"));
    image.src = src;
  });
}

/** The shared atlas, or null until it loads (or when it can't). */
export function useTileAtlas(): TileAtlas | null {
  const [atlas, setAtlas] = useState<TileAtlas | null>(null);
  useEffect(() => {
    let cancelled = false;
    void loadTileAtlas().then((loaded) => {
      if (!cancelled && loaded) setAtlas(loaded);
    });
    return () => {
      cancelled = true;
    };
  }, []);
  return atlas;
}

/** Test-only: clear the cached load so fetch/Image stubs take effect. */
export function __resetTileAtlasForTests(): void {
  atlasPromise = null;
}
