// Tileset v1 atlas: one baked sheet + UV manifest (apps/client/public/tiles,
// regenerated by scripts/build-tile-atlas.ps1). Loaded lazily as a static
// asset — never part of the JS bundle — and shared by every render surface
// (editor underlay today, the live table in R5). Families absent from the
// manifest (water, uploads) keep their flat fills.
import { useEffect, useState } from "react";
import { quarterTileVariant, type QuarterCorner } from "./blobAutotile";

export interface TileAtlasVariant {
  col: number;
  row: number;
}

export interface TileAtlasManifest {
  version: number;
  image: string;
  tileSize: number;
  columns: number;
  families: Record<
    string,
    {
      variants: TileAtlasVariant[];
      averageColor?: string;
      /**
       * Optional quarter-tile (blob47) sheet region for true 47-blob
       * autotiling. `col`/`row` are the region's ORIGIN in tile units. The
       * region is a `(4 + interiorVariants)`-wide × 4-tall grid of half-tile
       * quarters (64px at tileSize 128): columns 0..3 are the boundary
       * quarters (outer corner, horiz edge, vert edge, inner corner) and
       * columns 4..(4+interiorVariants-1) are INTERIOR detail variants, one
       * of which each fully-surrounded cell picks by spatial hash — see
       * `quarterRectsForCell`. `interiorVariants` defaults to 1 (single
       * interior column). Absent `blob47` ⇒ the family renders as whole tiles.
       */
      blob47?: { col: number; row: number; interiorVariants?: number };
    }
  >;
}

export interface TileAtlasRect {
  x: number;
  y: number;
  size: number;
}

/** Four quarter-tile source rects in fixed order: top-left, top-right,
 * bottom-left, bottom-right. */
export type TileAtlasQuarterRects = [TileAtlasRect, TileAtlasRect, TileAtlasRect, TileAtlasRect];

export interface TileAtlas {
  image: CanvasImageSource;
  tileForCell(assetId: string, cellX: number, cellY: number): TileAtlasRect | null;
  /**
   * Four quarter-tile source rects (tl, tr, bl, br) for a cell, or null when
   * the family has no `blob47` region. The rects are sliced from the family's
   * quarter-tile sheet by `quarterTileVariant`; the caller blits each to its
   * dest quarter (each half the cell size). See `createTileAtlas` for the
   * sheet layout.
   */
  quarterRectsForCell(
    assetId: string,
    cellX: number,
    cellY: number,
    neighborMask: number,
  ): TileAtlasQuarterRects | null;
}

/**
 * Deterministic spatial hash: the same cell always picks the same variant,
 * so painted maps look varied but stable across redraws, sessions, and
 * clients. Math.imul keeps 32-bit semantics for negative cell indices.
 */
export function variantIndexForCell(cellX: number, cellY: number, count: number): number {
  if (count <= 1) return 0;
  const hash = (Math.imul(cellX, 73856093) ^ Math.imul(cellY, 19349663)) >>> 0;
  return hash % count;
}

export function createTileAtlas(manifest: TileAtlasManifest, image: CanvasImageSource): TileAtlas {
  return {
    image,
    tileForCell(assetId, cellX, cellY) {
      const family = manifest.families[assetId];
      if (!family || family.variants.length === 0) return null;
      const variant = family.variants[variantIndexForCell(cellX, cellY, family.variants.length)]!;
      return {
        x: variant.col * manifest.tileSize,
        y: variant.row * manifest.tileSize,
        size: manifest.tileSize,
      };
    },
    // Sheet layout (the bake and the art MUST match this exactly). The family's
    // blob47 region begins at pixel (col*tileSize, row*tileSize) and is a grid
    // of half-tile quarters (q = tileSize/2), with the quarter COLUMN across X
    // and the CORNER down Y:
    //
    //          col 0     col 1    col 2    col 3    col 4..(4+N-1)
    //          variant0  variant1 variant2 variant3 INTERIOR variants 0..N-1
    //          (outer)   (horiz)  (vert)   (inner)  (fully-surrounded fill)
    //   row 0 tl  [ q x q ] ...
    //   row 1 tr  ...
    //   row 2 bl  ...
    //   row 3 br  ...
    //
    // A boundary quarter (variant 0..3) sits at column = variant. A fully-
    // surrounded quarter (variant 4) instead reads one of the N interior
    // detail columns, chosen by a per-cell spatial hash (variantIndexForCell)
    // so open fields get scattered detail (tufts/flowers) rather than one
    // repeating tile. All four quarters of a cell share the same hash, so the
    // interior stays a coherent tile. interiorVariants defaults to 1.
    quarterRectsForCell(assetId, cellX, cellY, neighborMask) {
      const family = manifest.families[assetId];
      if (!family?.blob47) return null;
      const quarter = manifest.tileSize / 2;
      const originX = family.blob47.col * manifest.tileSize;
      const originY = family.blob47.row * manifest.tileSize;
      const interiorCount = family.blob47.interiorVariants ?? 1;
      const interiorCol =
        4 + (interiorCount > 1 ? variantIndexForCell(cellX, cellY, interiorCount) : 0);
      const slice = (corner: QuarterCorner, cornerRow: number): TileAtlasRect => {
        const variant = quarterTileVariant(neighborMask, corner);
        const col = variant < 4 ? variant : interiorCol;
        return { x: originX + col * quarter, y: originY + cornerRow * quarter, size: quarter };
      };
      return [slice("tl", 0), slice("tr", 1), slice("bl", 2), slice("br", 3)];
    },
  };
}

const TILESET_MANIFEST_URL = "/tiles/tileset-v1.json";

let atlasPromise: Promise<TileAtlas | null> | null = null;

/**
 * Load the bundled tileset once per session. Resolves null on any failure
 * (offline, missing files) — consumers fall back to flat fills, never throw.
 */
export function loadTileAtlas(): Promise<TileAtlas | null> {
  atlasPromise ??= fetchTileAtlas();
  return atlasPromise;
}

async function fetchTileAtlas(): Promise<TileAtlas | null> {
  try {
    const response = await fetch(TILESET_MANIFEST_URL);
    if (!response.ok) return null;
    const manifest = (await response.json()) as TileAtlasManifest;
    const image = await loadAtlasImage(`/tiles/${manifest.image}`);
    return createTileAtlas(manifest, image);
  } catch {
    return null;
  }
}

function loadAtlasImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error("Unable to load tile atlas image"));
    image.src = src;
  });
}

/** The shared atlas, or null until it loads (or when it can't). */
export function useTileAtlas(): TileAtlas | null {
  const [atlas, setAtlas] = useState<TileAtlas | null>(null);
  useEffect(() => {
    let cancelled = false;
    void loadTileAtlas().then((loaded) => {
      if (!cancelled && loaded) setAtlas(loaded);
    });
    return () => {
      cancelled = true;
    };
  }, []);
  return atlas;
}

/** Test-only: clear the cached load so fetch/Image stubs take effect. */
export function __resetTileAtlasForTests(): void {
  atlasPromise = null;
}
