import type { LessonScript } from "../script";

// Every on-screen word here restates what Wren says or what video-scripts.md captions; nothing
// claims more than the lesson does. Cues are phrases from the narration or captured actions.
const say = (s: string, off = 0, end = false) => ({ say: s, off, end });
const mark = (m: string, off = 0, who = "dm") => ({ mark: m, off, who });

export const dmQuickStart: LessonScript = {
  slug: "dm-quick-start-set-up-your-table-before-game-night",
  title: "DM QUICK START",
  subtitle: "Set up your table before game night",
  outro: {
    headline: "READY FOR GAME NIGHT!",
    next: "More lessons and the full guides: herobyte.pages.dev/help",
  },
  chapters: [
    {
      title: "Make a table",
      zooms: [
        { from: say("Press New Table"), to: say("Give it a name", -0.3), target: { mark: "NEW TABLE", nth: 2 }, scale: 1.9 },
        { from: say("Give it a name"), to: say("Press Create", -0.4), target: { mark: "Table password" }, scale: 1.55 },
        { from: say("Press Create"), to: mark("table open", 0.3), target: { mark: "CREATE PRIVATE TABLE" }, scale: 1.8 },
      ],
      beats: [
        {
          kind: "popup",
          from: say("Real games live"),
          to: say("Press New Table", -0.3),
          icon: "🔒",
          title: "PRIVATE TABLE",
          lines: ["Its own passwords", "Never cleared automatically"],
          lineAt: [say("its own passwords"), say("never cleared")],
          pos: { x: 1450, y: 470 },
          width: 600,
        },
        { kind: "ring", from: say("Press New Table", -0.1), to: say("Give it a name", -0.4), target: { mark: "NEW TABLE", nth: 2 } },
        { kind: "popup", from: say("Give it a name"), to: say("Choose a table password", -0.25), icon: "✏️", title: "NAME IT", lines: ["One you'll recognise"], target: { mark: "Table name" }, side: "right", width: 470 },
        {
          kind: "popup",
          from: say("Choose a table password"),
          to: say("Choose a DM password", -0.25),
          icon: "🔑",
          title: "TABLE PASSWORD",
          lines: ["Your players type this one", "6+ characters"],
          lineAt: [say("Your players"), say("this one")],
          target: { mark: "Table password" },
          side: "right",
          width: 560,
        },
        {
          kind: "popup",
          from: say("Choose a DM password"),
          to: say("Press Create", -0.25),
          icon: "👑",
          tone: "blue",
          title: "DM PASSWORD",
          lines: ["Whoever knows it runs the table", "8+ characters"],
          lineAt: [say("Whoever knows it"), say("run the table")],
          target: { mark: "DM password" },
          side: "right",
          width: 600,
        },
        { kind: "ring", from: say("Press Create", -0.1), to: mark("CREATE PRIVATE TABLE", 0.7), target: { mark: "CREATE PRIVATE TABLE" } },
        { kind: "sticker", from: mark("table open"), to: mark("table open", 2.2), text: "✓ TABLE CREATED", pos: { x: 960, y: 520 }, tone: "green" },
      ],
    },
    {
      title: "Claim the DM seat",
      zooms: [
        { from: say("This card"), to: say("Press Enter DM mode", 1.2), target: { mark: "Next steps card" }, scale: 1.7 },
        { from: say("type your DM password"), to: mark("ENTER DM MODE", 0.4), target: { mark: "DM password" }, scale: 1.5 },
        { from: say("table button", -0.3), to: say("top left", 0.8, true), target: { mark: "Table button" }, scale: 2.0 },
      ],
      beats: [
        { kind: "popup", from: 0.1, to: say("This card", -0.3), icon: "🎲", title: "YOU START AS A PLAYER", pos: { x: 1380, y: 600 }, width: 640 },
        { kind: "ring", from: say("This card"), to: say("Press Enter DM mode", -0.3), target: { mark: "Next steps card" } },
        {
          kind: "popup",
          from: say("two next steps"),
          to: say("Press Enter DM mode", -0.3),
          icon: "📋",
          title: "TWO NEXT STEPS",
          lines: ["1 · Enter DM mode", "2 · Invite players", "Nothing happens by itself"],
          lineAt: [say("two next steps", 0.3), say("two next steps", 0.6), say("Nothing on it")],
          target: { mark: "Next steps card" },
          side: "below",
          width: 600,
        },
        { kind: "ring", from: say("Press Enter DM mode", -0.1), to: mark("Enter DM mode", 0.6), target: { mark: "Enter DM mode" } },
        { kind: "popup", from: say("type your DM password"), to: mark("ENTER DM MODE"), icon: "👑", tone: "blue", title: "DM PASSWORD", target: { mark: "DM password" }, side: "right", width: 470 },
        { kind: "title", from: mark("DM mode on"), to: mark("DM mode on", 2.0), text: "YOU ARE THE DM!", y: 430 },
        { kind: "popup", from: say("table button"), to: say("top left", 0.9, true), icon: "↖️", title: "SAME THING, ANY TIME", lines: ["The Table button, top left"], target: { mark: "Table button" }, side: "below", width: 560 },
      ],
    },
    {
      title: "Put a map down",
      end: mark("framed", 2.4),
      zooms: [
        { from: say("DM menu"), to: say("under Maps", -0.2), target: { mark: "DM MENU" }, scale: 1.8 },
        { from: say("under Maps"), to: say("To build one here", 0.2), target: { mark: "Maps" }, scale: 1.4 },
        { from: say("open Build Map"), to: say("press Start Live Map", -0.2), target: { mark: "Build map" }, scale: 1.9 },
        { from: say("press Start Live Map"), to: say("The map stays live", 0.4), target: { mark: "START LIVE MAP" }, scale: 1.7 },
        { from: say("Pick a recipe", -0.2), to: mark("Generate & enter", 0.5), target: { mark: "Kick in a door" }, scale: 1.55 },
      ],
      beats: [
        {
          kind: "ways",
          from: say("three ways"),
          to: say("Pick a recipe", -0.3),
          dock: say("If you have a map image", -0.3),
          ways: ["UPLOAD AN IMAGE", "BUILD IT LIVE", "KICK IN A DOOR"],
          active: [say("If you have a map image"), say("To build one here"), say("the third way")],
        },
        { kind: "popup", from: say("Lesson 3", -0.2), to: say("To build one here", -0.2), icon: "🖼️", title: "UPLOAD IMAGE", lines: ["Lesson 3 covers it"], target: { mark: "Upload image" }, side: "auto", width: 470 },
        { kind: "ring", from: say("open Build Map", 0.1), to: mark("Build map", 0.6), target: { mark: "Build map" } },
        { kind: "ring", from: say("press Start Live Map"), to: mark("START LIVE MAP", 0.6), target: { mark: "START LIVE MAP" } },
        { kind: "key", from: say("Escape"), to: say("Escape", 1.8), label: "ESC", sfx: "ui-close.wav" },
        { kind: "sticker", from: say("The map stays live"), to: say("And the third way", -0.2), text: "● THE MAP STAYS LIVE", pos: { x: 760, y: 560 }, tone: "green" },
        { kind: "spot", from: say("And the third way"), to: say("Now press G", -0.1), radius: 520 },
        { kind: "title", from: say("the fun one"), to: say("Now press G", -0.1), text: "...THE FUN ONE", y: 380, sfx: "ping.wav" },
        { kind: "key", from: say("G"), to: say("G", 1.6), label: "G", sfx: "door-slam.wav", shake: true, pos: { x: 960, y: 470 } },
        { kind: "title", from: say("kicked -in door"), to: say("Pick a recipe", -0.15), text: "THE KICKED-IN DOOR", sub: "Pick a recipe. Generate. You're there.", y: 330, sfx: "door-creak.wav" },
        {
          kind: "chips",
          to: mark("Generate & enter", 0.4),
          pos: { x: 960, y: 800 },
          items: [
            { text: "BUILDING", at: mark("Recipe") },
            { text: "TAVERN", at: mark("Kind") },
            { text: "SMALL", at: mark("Size") },
            { text: "THE SALT HOUND", at: mark("Name") },
          ],
        },
        { kind: "ring", from: say("press Generate", -0.1), to: mark("Generate & enter", 0.5), target: { mark: "Generate & enter" } },
        { kind: "title", from: mark("arrived", 0.3), to: mark("framed", 2.2), text: "THE SALT HOUND", y: 800, sfx: "heal.wav" },
      ],
    },
    {
      title: "Send the invite",
      split: { from: say("Send the password", -0.2), labels: ["DM", "PLAYER"] },
      zooms: [
        { from: say("Invite Players", -0.3), to: say("It copies the link", 0.9), target: { mark: "Invite players" }, scale: 1.8 },
        { from: say("DM menu"), to: say("under Table", -0.2), target: { mark: "DM MENU" }, scale: 1.8 },
        { from: say("under Table"), to: say("Send the password", -0.4), target: { mark: "Copy invite link" }, scale: 1.5 },
      ],
      beats: [
        { kind: "ring", from: say("Invite Players", -0.1), to: say("It copies the link", 0.8), target: { mark: "Invite players" } },
        {
          kind: "popup",
          from: say("because you are the DM"),
          to: say("Later", -0.2),
          icon: "🔗",
          title: "INVITE PLAYERS",
          lines: ["Works now: you're the DM", "Copies the link"],
          lineAt: [say("because you are the DM"), say("It copies the link")],
          target: { mark: "Invite players" },
          side: "below",
          width: 560,
        },
        {
          kind: "chips",
          to: say("Send the password", -0.3),
          pos: { x: 960, y: 800 },
          sep: "›",
          items: [
            { text: "DM MENU", at: say("DM menu") },
            { text: "TABLE", at: say("under Table") },
            { text: "INVITE", at: say("then Invite") },
          ],
        },
        {
          kind: "chips",
          to: say("Unless you enjoy", -0.2),
          pos: { x: 960, y: 92 },
          sep: "+",
          tone: "blue",
          items: [
            { text: "🔗 THE LINK", at: say("Send the password", 0.2) },
            { text: "🔑 THE PASSWORD, SEPARATELY", at: say("separately") },
          ],
        },
        { kind: "sticker", from: say("does not carry it", -0.4), to: say("Unless you enjoy", -0.2), text: "THE LINK CARRIES NO PASSWORD", pos: { x: 960, y: 820 }, tone: "gold", tilt: -2 },
        { kind: "ring", from: mark("Table password", 0, "player"), to: mark("ENTER TABLE", 0.5, "player"), target: { mark: "Table password", who: "player" } },
        { kind: "spam", from: say("Unless you enjoy"), to: say("10 minutes", 0.6, true), text: "what's the password?", count: 7, every: 7 },
        { kind: "sticker", from: say("next 10 minutes"), to: say("10 minutes", 0.6, true), text: "⏱ FOR 10 MINUTES", pos: { x: 1500, y: 800 }, tone: "blue", tilt: 5 },
        { kind: "sticker", from: mark("player in", 0.6, "player"), to: mark("player in", 2.6, "player"), text: "✓ PLAYER IN!", pos: { x: 1424, y: 820 }, tone: "green" },
      ],
    },
    {
      title: "See what they see",
      split: { from: say("You now see", -0.1), labels: ["YOUR PLAYER VIEW", "THE PLAYER'S SCREEN"] },
      zooms: [{ from: 0, to: say("You now see", -0.3), target: { mark: "Player View" }, scale: 1.9 }],
      beats: [
        { kind: "ring", from: 0, to: mark("Player View", 0.6), target: { mark: "Player View" } },
        {
          kind: "chips",
          to: say("You keep every", -0.2),
          pos: { x: 960, y: 110 },
          items: [
            { text: "🌫 FOG FROM THE PARTY'S VISION", at: say("Fog") },
            { text: "🚪 SECRET DOORS HIDDEN", at: say("secret doors") },
          ],
        },
        { kind: "sticker", from: say("You keep every"), to: say("Press it again", -0.2), text: "👑 YOU KEEP EVERY DM POWER", pos: { x: 960, y: 820 }, tone: "blue", tilt: -2 },
        { kind: "ring", from: say("Press it again", -0.1), to: mark("Player View", 0.6), target: { mark: "Player View", nth: 2 } },
        { kind: "sticker", from: say("switch back", -0.1), to: say("Player View is on", -0.2), text: "ONE CLICK ON · ONE CLICK OFF", pos: { x: 960, y: 820 }, tone: "gold", tilt: 2 },
        { kind: "sticker", from: say("Player View is on"), to: say("layout", 1.4, true), text: "💻 COMPUTER LAYOUT ONLY", pos: { x: 960, y: 820 }, tone: "green", tilt: -3 },
      ],
    },
  ],
};
