import type { LessonScript } from "../script";

// Every on-screen word restates what Wren says or what video-scripts.md captions.
const say = (s: string, off = 0, end = false) => ({ say: s, off, end });
const mark = (m: string, off = 0, who = "player") => ({ mark: m, off, who });
const t = (m: string, who = "player", nth = 1) => ({ mark: m, who, nth });

export const playerQuickStart: LessonScript = {
  slug: "player-quick-start-your-first-session-as-a-player",
  title: "PLAYER QUICK START",
  subtitle: "Your first session as a player",
  captionFixes: { "sell.": "cell.", "D20,": "d20,", "DICE": "Dice" },
  outro: {
    headline: "READY TO PLAY!",
    next: "More lessons and the full guides: herobyte.pages.dev/help",
  },
  chapters: [
    {
      title: "Get in",
      zooms: [
        { from: say("Check the connection"), to: say("Type the table", -0.3), target: t("Connection status"), scale: 1.9, who: "player" },
        { from: say("Type the table"), to: say("Press Enter", -0.3), target: t("Table password"), scale: 1.6, who: "player" },
        { from: say("Press Enter"), to: mark("joined", 0.4), target: t("ENTER TABLE"), scale: 1.7, who: "player" },
      ],
      beats: [
        { kind: "spot", from: say("Your DM sends"), to: say("Open the link", -0.2), radius: 1300 },
        {
          kind: "chips",
          to: say("Open the link", -0.3),
          pos: { x: 960, y: 400 },
          sep: "+",
          items: [
            { text: "🔗 A LINK", at: say("a link") },
            { text: "🔑 A PASSWORD", at: say("a password") },
          ],
        },
        { kind: "sticker", from: say("separately"), to: say("The link never", -0.2), text: "THEY COME SEPARATELY", pos: { x: 960, y: 560 }, tone: "blue", tilt: -3 },
        { kind: "sticker", from: say("The link never"), to: say("Open the link", -0.3), text: "THE LINK NEVER CARRIES THE PASSWORD", pos: { x: 960, y: 560 }, tone: "gold", tilt: 2 },
        { kind: "sticker", from: say("Open the link"), to: say("Check the connection", -0.2), text: "🔗 OPEN THE LINK", pos: { x: 960, y: 200 }, tone: "blue" },
        { kind: "ring", from: say("Check the connection"), to: say("Type the table", -0.4), target: t("Connection status") },
        { kind: "popup", from: say("It should say", -0.2), to: say("Type the table", -0.4), icon: "🟢", tone: "green", title: "CONNECTED", lines: ["The connection status line"], target: t("Connection status"), side: "right", width: 520 },
        {
          kind: "popup",
          from: say("Type the table"),
          to: say("Press Enter", -0.3),
          icon: "🔑",
          title: "TABLE PASSWORD",
          lines: ["From your DM, not the link", "Case-sensitive"],
          lineAt: [say("Type the table", 0.6), say("case sensitive")],
          target: t("Table password"),
          side: "right",
          width: 560,
        },
        { kind: "ring", from: say("Press Enter", -0.1), to: mark("ENTER TABLE", 0.6), target: t("ENTER TABLE") },
        { kind: "sticker", from: mark("joined", 0.3), to: mark("joined", 2.0), text: "✓ YOU'RE IN!", pos: { x: 960, y: 520 }, tone: "green" },
      ],
    },
    {
      title: "Find yourself",
      zooms: [
        { from: 0, to: say("Your character has a row", -0.3), target: t("token"), scale: 1.8 },
        { from: say("Your character has a row"), to: say("Lost your token", -0.2), target: t("your row"), scale: 1.7 },
        { from: say("target button", -0.2), to: say("Select your row", -0.2), target: t("Focus"), scale: 1.8 },
        { from: say("Click your name", -0.2), to: say("drag along the bar", 1.6), target: t("name"), scale: 1.6 },
      ],
      beats: [
        { kind: "ring", from: 0.1, to: say("Your character has a row", -0.3), target: t("token") },
        { kind: "popup", from: 0.2, to: say("Your character has a row", -0.3), icon: "🧙", title: "YOUR TOKEN", target: t("token"), side: "right", width: 440 },
        {
          kind: "popup",
          from: say("Your character has a row"),
          to: say("Lost your token", -0.3),
          icon: "📋",
          title: "YOUR ROW",
          lines: ["In the Party, at the bottom", "It reads “You”"],
          lineAt: [say("at the bottom"), say("reads")],
          target: t("your row"),
          side: "above",
          width: 520,
        },
        { kind: "sticker", from: say("Lost your token"), to: say("Press the target", -0.1), text: "LOST IT?", pos: { x: 960, y: 420 }, tone: "blue", tilt: -5 },
        { kind: "ring", from: say("Press the target"), to: mark("Focus", 0.6), target: t("Focus") },
        { kind: "popup", from: say("target button"), to: say("Select your row", -0.3), icon: "🎯", title: "TARGET BUTTON", lines: ["The map jumps to your token"], target: t("Focus"), side: "above", width: 560 },
        { kind: "ring", from: say("Select your row", -0.1), to: mark("row", 0.8), target: t("row") },
        { kind: "sticker", from: say("open your character card"), to: say("Click your name", -0.2), text: "YOUR CHARACTER CARD", pos: { x: 960, y: 420 }, tone: "gold" },
        { kind: "popup", from: say("Click your name"), to: say("Click a number", -0.3), icon: "✏️", title: "RENAME", lines: ["Click your name"], target: t("name"), side: "left", width: 440 },
        {
          kind: "popup",
          from: say("Click a number"),
          to: say("drag along the bar", 1.6),
          icon: "❤️",
          tone: "red",
          title: "HIT POINTS",
          lines: ["Click a number to type", "Or drag along the bar"],
          lineAt: [say("number in HP"), say("drag along")],
          target: t("HP number"),
          side: "left",
          width: 520,
        },
      ],
    },
    {
      title: "Move",
      phone: { from: say("On a phone", -0.3), label: "PHONE" },
      zooms: [
        { from: 0, to: say("Turn snap on", -0.2), target: t("token"), scale: 1.5 },
        { from: say("Turn snap on"), to: say("clicks to the grid", -0.3), target: t("Snap"), scale: 1.8 },
      ],
      beats: [
        { kind: "popup", from: 0.3, to: say("Turn snap on", -0.3), icon: "✋", title: "DRAG TO MOVE", target: t("token"), side: "right", width: 460 },
        { kind: "ring", from: say("Turn snap on", -0.1), to: mark("Snap", 0.7), target: t("Snap") },
        { kind: "popup", from: say("snap on"), to: say("Everyone sees", -0.2), icon: "🧲", title: "SNAP", lines: ["Clicks to the grid"], target: t("Snap"), side: "below", width: 440 },
        { kind: "sticker", from: say("Everyone sees"), to: say("You can also", -0.2), text: "EVERYONE SEES IT WHEN YOU LET GO", pos: { x: 960, y: 420 }, tone: "green", tilt: -2 },
        { kind: "key", from: say("W"), to: say("One press", -0.2), label: "W", pos: { x: 630, y: 360 }, sfx: "button-blip.wav" },
        { kind: "key", from: say("A"), to: say("One press", -0.2), label: "A", pos: { x: 850, y: 360 }, sfx: "button-blip.wav" },
        { kind: "key", from: say("S"), to: say("One press", -0.2), label: "S", pos: { x: 1070, y: 360 }, sfx: "button-blip.wav" },
        { kind: "key", from: say("D"), to: say("One press", -0.2), label: "D", pos: { x: 1290, y: 360 }, sfx: "button-blip.wav" },
        { kind: "sticker", from: say("arrow keys"), to: say("One press", -0.2), text: "OR THE ARROW KEYS", pos: { x: 960, y: 560 }, tone: "blue" },
        { kind: "sticker", from: say("One press"), to: say("On a phone", -0.4), text: "ONE PRESS = ONE CELL", pos: { x: 960, y: 420 }, tone: "gold", tilt: 3 },
        {
          kind: "chips",
          to: say("D -pad", 2.4, true),
          pos: { x: 650, y: 880 },
          sep: "›",
          items: [
            { text: "TOOLS", at: say("open tools") },
            { text: "SELECT", at: say("then select") },
            { text: "TAP YOUR TOKEN", at: say("Tap your token") },
            { text: "D-PAD", at: say("D -pad") },
          ],
        },
        { kind: "ring", from: say("open tools", -0.1), to: mark("TOOLS", 0.6, "phone"), target: t("TOOLS", "phone") },
        { kind: "ring", from: say("Tap your token", -0.1), to: mark("token", 0.8, "phone"), target: t("token", "phone") },
        { kind: "ring", from: say("D -pad"), to: say("D -pad", 2.4, true), target: t("Move right", "phone") },
      ],
    },
    {
      title: "Roll",
      zooms: [
        { from: say("Press DICE", -0.2), to: say("Click a die", -0.3), target: t("Dice"), scale: 1.9 },
        { from: say("Click a die"), to: say("Pick normal", -0.3), target: t("Add d20"), scale: 1.5 },
        { from: say("Pick normal"), to: say("who sees it", -0.2), target: t("Roll mode"), scale: 1.7 },
        { from: say("who sees it"), to: say("Press Roll", -0.2), target: t("Who sees this roll"), scale: 1.7 },
        { from: say("Roll Now row", -0.3), to: say("Rolling real dice", -0.2), target: t("Roll now d20"), scale: 1.7 },
        { from: say("I rolled it", -0.3), to: say("The log", -0.1), target: t("I ROLLED IT"), scale: 1.6 },
        { from: say("by hand", -0.3), to: say("by hand", 2.0, true), target: t("BY HAND"), scale: 2.0 },
      ],
      beats: [
        { kind: "ring", from: say("Press DICE", -0.1), to: mark("Dice", 0.6), target: t("Dice") },
        {
          kind: "popup",
          from: say("Click a die"),
          to: say("Add a modifier", -0.2),
          icon: "🎲",
          title: "ADD A DIE",
          lines: ["Again for more of the same"],
          lineAt: [say("Click again")],
          target: t("Add d20"),
          side: "auto",
          width: 520,
        },
        { kind: "popup", from: say("modifier chip"), to: say("Pick normal", -0.3), icon: "➕", title: "MODIFIER", lines: ["If you need one"], target: t("+1"), side: "auto", width: 440 },
        {
          kind: "chips",
          to: say("who sees it", -0.3),
          pos: { x: 960, y: 220 },
          items: [
            { text: "NORMAL", at: say("Pick normal", 0.3) },
            { text: "ADV = ADVANTAGE", at: say("ADV") },
            { text: "DIS = DISADVANTAGE", at: say("DIS") },
          ],
        },
        {
          kind: "chips",
          to: say("Press Roll", -0.2),
          pos: { x: 960, y: 220 },
          tone: "blue",
          items: [
            { text: "THE TABLE", at: say("the table") },
            { text: "THE DM", at: say("the DM") },
            { text: "ONLY YOU", at: say("only you") },
          ],
        },
        { kind: "ring", from: say("Press Roll", -0.1), to: mark("ROLL!", 0.7), target: t("ROLL!") },
        { kind: "sfx", at: mark("ROLL!", 0.1), src: "dice-rattle.wav", volume: 0.4 },
        { kind: "sfx", at: mark("ROLL!", 1.1), src: "dice-land.wav", volume: 0.4 },
        { kind: "popup", from: say("Roll Now row"), to: say("Rolling real dice", -0.3), icon: "⚡", title: "ROLL NOW", lines: ["One press, one roll"], lineAt: [say("One press")], target: t("Roll now d20"), side: "auto", width: 480 },
        { kind: "ring", from: say("I rolled it", -0.2), to: mark("I ROLLED IT", 0.7), target: t("I ROLLED IT") },
        { kind: "popup", from: say("Rolling real dice"), to: say("The log", -0.2), icon: "✋", title: "REAL DICE?", lines: ["Press I rolled it", "Type what you got"], lineAt: [say("I rolled it"), say("type what you got")], target: t("I ROLLED IT"), side: "auto", width: 500 },
        { kind: "ring", from: say("by hand", -0.2), to: say("by hand", 2.0, true), target: t("BY HAND") },
        { kind: "sticker", from: say("by hand"), to: say("by hand", 2.0, true), text: "MARKED “BY HAND”", pos: { x: 960, y: 820 }, tone: "gold", tilt: -3 },
      ],
    },
  ],
};
