// ============================================================================
// FROZEN CONTRACT — DO NOT EDIT THIS FILE.
//
// These golden tests pin the export byte-parity contract:
// renderMapDocumentSvg (via buildTerrainRenderLayers) must emit byte-identical
// path strings for every possible MapDocument, release over release. The
// exact separators, per-cell edge emit order (top, bottom, left, right),
// number formatting, and H/V command letters below were captured from the
// pre-refactor implementation and verified by adversarial review.
//
// This file's hash is enforced by `node scripts/check-frozen-tests.mjs`,
// which runs inside `pnpm lint`. If your change makes these tests fail, the
// bug is in YOUR CODE — fix the code, never this file. If the contract itself
// is being changed, that is a PROJECT-OWNER decision: the owner edits this
// file and runs `node scripts/check-frozen-tests.mjs --update`.
// ============================================================================
import { describe, expect, it } from "vitest";
import { createMapDocument, paintTerrain } from "@herobyte/shared";
import { buildTileOccupancy } from "../tileAutotiling";
import { buildTerrainRenderLayers } from "../terrainRender";

const GRID = { size: 50, offsetX: 0, offsetY: 0 };

function painted(cells: Array<{ x: number; y: number; assetId: string }>) {
  let document = createMapDocument({ id: "map", name: "Keep", timestamp: 1 });
  document = paintTerrain(document, cells, 2);
  return document;
}

describe("SVG path strings (export byte-parity pins — FROZEN)", () => {
  it("emits the exact fill and boundary strings for a mixed-terrain map", () => {
    const document = painted([
      { x: 2, y: 0, assetId: "terrain:water" },
      { x: 0, y: 0, assetId: "terrain:stone-floor" },
      { x: 1, y: 0, assetId: "terrain:stone-floor" },
      { x: 1, y: 1, assetId: "terrain:stone-floor" },
    ]);

    const layers = buildTerrainRenderLayers(document.terrain!, GRID, buildTileOccupancy(document));

    expect(layers).toMatchInlineSnapshot(`
      [
        {
          "assetId": "terrain:stone-floor",
          "boundaryPath": "M 0 0 H 50 M 0 50 H 50 M 0 0 V 50 M 50 0 H 100 M 100 0 V 50 M 50 100 H 100 M 50 50 V 100 M 100 50 V 100",
          "fillPath": "M 0 0 h 50 v 50 h -50 Z M 50 0 h 50 v 50 h -50 Z M 50 50 h 50 v 50 h -50 Z",
        },
        {
          "assetId": "terrain:water",
          "boundaryPath": "M 100 0 H 150 M 100 50 H 150 M 100 0 V 50 M 150 0 V 50",
          "fillPath": "M 100 0 h 50 v 50 h -50 Z",
        },
      ]
    `);
  });

  it("emits the exact strings on a fractional offset lattice", () => {
    const document = painted([
      { x: 0, y: 0, assetId: "terrain:water" },
      { x: 1, y: 0, assetId: "terrain:water" },
    ]);

    const layers = buildTerrainRenderLayers(
      document.terrain!,
      { size: 50, offsetX: 12.5, offsetY: 7.25 },
      buildTileOccupancy(document),
    );

    expect(layers).toMatchInlineSnapshot(`
      [
        {
          "assetId": "terrain:water",
          "boundaryPath": "M 12.5 7.25 H 62.5 M 12.5 57.25 H 62.5 M 12.5 7.25 V 57.25 M 62.5 7.25 H 112.5 M 62.5 57.25 H 112.5 M 112.5 7.25 V 57.25",
          "fillPath": "M 12.5 7.25 h 50 v 50 h -50 Z M 62.5 7.25 h 50 v 50 h -50 Z",
        },
      ]
    `);
  });

  it("keeps vertical edges 'V' when float absorption collapses the cell height", () => {
    // offsetY 1e18 passes sanitizeMapGrid, and 1e18 + 50 === 1e18 (ulp 128):
    // the edge collapses to a point, but orientation must not flip to 'H' —
    // the pre-refactor code chose the command letter structurally.
    const document = painted([{ x: 0, y: 0, assetId: "terrain:water" }]);

    const layers = buildTerrainRenderLayers(
      document.terrain!,
      { size: 50, offsetX: 0, offsetY: 1e18 },
      buildTileOccupancy(document),
    );

    expect(layers[0]!.fillPath).toBe("M 0 1000000000000000000 h 50 v 50 h -50 Z");
    expect(layers[0]!.boundaryPath).toBe(
      "M 0 1000000000000000000 H 50 M 0 1000000000000000000 H 50 " +
        "M 0 1000000000000000000 V 1000000000000000000 M 50 1000000000000000000 V 1000000000000000000",
    );
  });

  it("emits the exact strings for negative-coordinate cells", () => {
    const document = painted([
      { x: -1, y: -1, assetId: "terrain:grass" },
      { x: 0, y: -1, assetId: "terrain:grass" },
    ]);

    const layers = buildTerrainRenderLayers(document.terrain!, GRID, buildTileOccupancy(document));

    expect(layers).toMatchInlineSnapshot(`
      [
        {
          "assetId": "terrain:grass",
          "boundaryPath": "M -50 -50 H 0 M -50 0 H 0 M -50 -50 V 0 M 0 -50 H 50 M 0 0 H 50 M 50 -50 V 0",
          "fillPath": "M -50 -50 h 50 v 50 h -50 Z M 0 -50 h 50 v 50 h -50 Z",
        },
      ]
    `);
  });
});
