import { vi } from "vitest";
import type { MainLayoutProps } from "../../../layouts/props/MainLayoutProps";
type DrawingToolbarProps = MainLayoutProps["drawingToolbarProps"];
type DrawingProps = MainLayoutProps["drawingProps"];
type PlayerActions = MainLayoutProps["playerActions"];
// Existing MobileLayout baseline values, copied without extracting the old suite.
export const createKickMobileProps = (): MainLayoutProps => ({
  isConnected: true,
  topHeight: 0,
  bottomHeight: 0,
  topPanelRef: { current: null },
  bottomPanelRef: { current: null },
  contextMenu: null,
  setContextMenu: vi.fn(),
  activeTool: "pointer",
  setActiveTool: vi.fn(),
  drawMode: false,
  pointerMode: true,
  measureMode: false,
  transformMode: false,
  selectMode: false,
  alignmentMode: false,
  mapEditMode: false,
  mapEditActiveSubTool: "wall" as const,
  mapEditFloorFamily: "grass" as const,
  mapEditRoomWallFamily: "none" as const,
  mapEditSelectedAssetId: "objects:crate",
  mapEditHallwayWidth: 2,
  mapEditSelectedElementId: null,
  mapEditWallsOverlayPinned: false,
  onMapEditRoomRejected: vi.fn(),
  onMapEditGestureDropped: vi.fn(),
  onMapEditRegionPlaced: vi.fn(),
  onMapEditRegionDragged: vi.fn(),
  onMapEditSelectElement: vi.fn(),
  onMapEditSampleAsset: vi.fn(),
  mapEditToolbarProps: {
    isLive: false,
    busy: false,
    activeSubTool: "wall" as const,
    onSelectSubTool: vi.fn(),
    floorFamily: "grass" as const,
    onSelectFloorFamily: vi.fn(),
    roomWallFamily: "none" as const,
    onSelectRoomWallFamily: vi.fn(),
    canUndo: false,
    canRedo: false,
    onUndo: vi.fn(),
    onRedo: vi.fn(),
    onStartLiveMap: vi.fn(),
    onClose: vi.fn(),
    hasRasterBackground: false,
    error: null,
    wallsOverlayPinned: false,
    onToggleWallsOverlay: vi.fn(),
    selectedAssetId: "objects:crate",
    onSelectAsset: vi.fn(),
    uploadAsset: vi.fn(),
    assetPickerOpen: false,
    stampMode: false,
    onToggleStampMode: vi.fn(),
    stampRotation: 0,
    onRotateStamp: vi.fn(),
    onToggleAssetPicker: vi.fn(),
    hallwayWidth: 2,
    onSelectHallwayWidth: vi.fn(),
    splineKind: "rope" as const,
    onSelectSplineKind: vi.fn(),
    populateDensity: "medium" as const,
    onSelectPopulateDensity: vi.fn(),
    populateCategory: "objects" as const,
    onSelectPopulateCategory: vi.fn(),
    onPopulate: vi.fn(),
    canPopulate: false,
    generateParams: {
      theme: "stone" as const,
      density: "medium" as const,
      seed: 1,
    },
    onGenerateParamsChange: vi.fn(),
    onRerollSeed: vi.fn(),
    onGenerate: vi.fn(),
    canGenerate: false,
    generateRegion: null,
    generateHint: null,
    saving: false,
    layers: [],
    selectedElement: null,
    onUpdateLayer: vi.fn(),
    onMoveLayer: vi.fn(),
    onUpdateElement: vi.fn(),
    onUpdateDoor: vi.fn(),
    onRemoveElement: vi.fn(),
    layersOpen: false,
    onToggleLayers: vi.fn(),
    inspectorOpen: false,
    onToggleInspector: vi.fn(),
  },
  snapToGrid: true,
  setSnapToGrid: vi.fn(),
  crtFilter: false,
  setCrtFilter: vi.fn(),
  diceRollerOpen: false,
  rollLogOpen: false,
  toggleDiceRoller: vi.fn(),
  toggleRollLog: vi.fn(),
  micEnabled: false,
  toggleMic: vi.fn(),
  gridLocked: false,
  setGridLocked: vi.fn(),
  snapshot: { combatActive: false } as MainLayoutProps["snapshot"],
  uid: "test-uid",
  gridSize: 50,
  gridSquareSize: 5,
  isDM: false,
  cameraState: { x: 0, y: 0, scale: 1 },
  camera: { x: 0, y: 0, scale: 1 },
  cameraCommand: null,
  handleCameraCommandHandled: vi.fn(),
  setCameraState: vi.fn(),
  handleFocusToken: vi.fn(),
  handleResetCamera: vi.fn(),
  drawingToolbarProps: {} as DrawingToolbarProps,
  drawingProps: {} as DrawingProps,
  handleClearDrawings: vi.fn(),
  editingPlayerUID: null,
  nameInput: "",
  editingHpUID: null,
  hpInput: "",
  editingMaxHpUID: null,
  maxHpInput: "",
  editingTempHpUID: null,
  tempHpInput: "",
  updateNameInput: vi.fn(),
  startNameEdit: vi.fn(),
  submitNameEdit: vi.fn(),
  updateHpInput: vi.fn(),
  startHpEdit: vi.fn(),
  submitHpEdit: vi.fn(),
  updateMaxHpInput: vi.fn(),
  startMaxHpEdit: vi.fn(),
  submitMaxHpEdit: vi.fn(),
  updateTempHpInput: vi.fn(),
  startTempHpEdit: vi.fn(),
  submitTempHpEdit: vi.fn(),
  onCharacterPortraitUpdate: vi.fn(),
  selectedObjectId: null,
  selectedObjectIds: [],
  handleObjectSelection: vi.fn(),
  handleObjectSelectionBatch: vi.fn(),
  lockSelected: vi.fn(),
  unlockSelected: vi.fn(),
  selectPlayerTokens: vi.fn(),
  playerActions: {} as PlayerActions,
  mapSceneObject: null,
  stagingZoneSceneObject: null,
  recolorToken: vi.fn(),
  transformSceneObject: vi.fn(),
  toggleSceneObjectLock: vi.fn(),
  deleteToken: vi.fn(),
  updateTokenImage: vi.fn(),
  updateTokenSize: vi.fn(),
  alignmentPoints: [],
  alignmentSuggestion: null,
  alignmentError: null,
  handleAlignmentStart: vi.fn(),
  handleAlignmentReset: vi.fn(),
  handleAlignmentCancel: vi.fn(),
  handleAlignmentApply: vi.fn(),
  handleAlignmentPointCapture: vi.fn(),
  rollHistory: [],
  chatMessages: [],
  handleSendChat: vi.fn(),
  viewingRoll: null,
  handleRoll: vi.fn(),
  handleEnterRoll: vi.fn(),
  canEnterOver: vi.fn(() => true),
  latestOwnRoll: null,
  handleClearLog: vi.fn(),
  handleViewRoll: vi.fn(),
  handleSetRoomPassword: vi.fn(),
  roomPasswordStatus: null,
  roomPasswordPending: false,
  dismissRoomPasswordStatus: vi.fn(),
  handleToggleDM: vi.fn(),
  setMapBackgroundURL: vi.fn(),
  setGridSize: vi.fn(),
  setGridSquareSize: vi.fn(),
  toast: {
    messages: [],
    success: vi.fn(),
    error: vi.fn(),
    warning: vi.fn(),
    info: vi.fn(),
    dismiss: vi.fn(),
  },
  sendMessage: vi.fn(),
});
