// ============================================================================
// SFX MANIFEST
// ============================================================================
// Names the game's one-shot sound effects and their default playback params.
// Each entry points at a low-bitrate WAV sample served from /sfx (generated by
// scripts/generate-sfx.mjs). Because these are real sample buffers, any file
// can be swapped for a hand-recorded one-shot and it inherits the same S-DSP
// echo treatment automatically.

export type SfxName =
  | "diceRattle"
  | "diceLand"
  | "critSting"
  | "failThud"
  | "damage"
  | "heal"
  | "buttonBlip"
  | "tokenPlace"
  | "turnAdvance"
  | "ping"
  | "uiOpen"
  | "uiClose"
  | "doorCreak"
  | "doorClunk";

export interface SfxSpec {
  /** URL of the WAV sample, relative to the site root. */
  url: string;
  /** Base gain 0..1 applied on top of master volume. */
  gain: number;
  /** Base playback rate (pitch). 1 = as-recorded. */
  rate: number;
  /** Random +/- pitch variation so repeats don't feel robotic. */
  rateJitter: number;
  /** How much of this sound feeds the S-DSP echo bus, 0..1. */
  reverbSend: number;
}

const base = "/sfx";

export const SFX_MANIFEST: Record<SfxName, SfxSpec> = {
  diceRattle: {
    url: `${base}/dice-rattle.wav`,
    gain: 0.5,
    rate: 1,
    rateJitter: 0.06,
    reverbSend: 0.15,
  },
  diceLand: {
    url: `${base}/dice-land.wav`,
    gain: 0.7,
    rate: 1,
    rateJitter: 0.08,
    reverbSend: 0.25,
  },
  critSting: { url: `${base}/crit-sting.wav`, gain: 0.7, rate: 1, rateJitter: 0, reverbSend: 0.45 },
  failThud: { url: `${base}/fail-thud.wav`, gain: 0.7, rate: 1, rateJitter: 0.03, reverbSend: 0.4 },
  damage: { url: `${base}/damage.wav`, gain: 0.6, rate: 1, rateJitter: 0.1, reverbSend: 0.2 },
  heal: { url: `${base}/heal.wav`, gain: 0.55, rate: 1, rateJitter: 0.04, reverbSend: 0.35 },
  buttonBlip: {
    url: `${base}/button-blip.wav`,
    gain: 0.35,
    rate: 1,
    rateJitter: 0.05,
    reverbSend: 0.1,
  },
  tokenPlace: {
    url: `${base}/token-place.wav`,
    gain: 0.45,
    rate: 1,
    rateJitter: 0.08,
    reverbSend: 0.15,
  },
  turnAdvance: {
    url: `${base}/turn-advance.wav`,
    gain: 0.6,
    rate: 1,
    rateJitter: 0,
    reverbSend: 0.3,
  },
  ping: { url: `${base}/ping.wav`, gain: 0.4, rate: 1, rateJitter: 0.05, reverbSend: 0.35 },
  uiOpen: { url: `${base}/ui-open.wav`, gain: 0.4, rate: 1, rateJitter: 0, reverbSend: 0.15 },
  uiClose: { url: `${base}/ui-close.wav`, gain: 0.4, rate: 1, rateJitter: 0, reverbSend: 0.15 },
  doorCreak: {
    url: `${base}/door-creak.wav`,
    gain: 0.55,
    rate: 1,
    rateJitter: 0.07,
    reverbSend: 0.4,
  },
  doorClunk: {
    url: `${base}/door-clunk.wav`,
    gain: 0.6,
    rate: 1,
    rateJitter: 0.05,
    reverbSend: 0.3,
  },
};

export const ALL_SFX_NAMES = Object.keys(SFX_MANIFEST) as SfxName[];
