// Bundled STRUCTURAL tile assets — the legacy block, painted walls, stairs,
// roofs and dais — split from starterTileAssets for the 350-LOC cap (same
// pattern as starterTileObjectAssets). starterTileAssets spreads this array
// into MAP_STUDIO_TILE_ASSETS, so callers keep importing from
// "./starterTiles" and never see the split.

import type { MapStudioTileAsset } from "./starterTileAssets";

export const STRUCTURE_TILE_ASSETS: MapStudioTileAsset[] = [
  {
    // Legacy flat placeable block — the PAINTED wall families below are the
    // "walls that look like walls" (procedural top + rim + cast shadow).
    id: "structures:stone-wall",
    name: "Stone Block",
    category: "structures",
    layerKind: "walls",
    columns: 1,
    rows: 1,
    fill: "#64606a",
    stroke: "#9e96a5",
    accent: "#3f3b45",
  },
  // Painted wall families (Czepeku-style band walls). Fills match their
  // VILLAGE_TERRAIN bases (pinned by wallVariants.test) so the field bake and
  // the flat fallback/SVG export agree.
  {
    id: "terrain:wall-stone",
    name: "Stone Wall",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#b3a687",
    stroke: "#cabfa2",
    accent: "#4e4638",
    material: "stone",
    brushNote: "Tall stone band — lit top, inked rim, cast shadow",
  },
  {
    id: "terrain:wall-brick",
    name: "Brick Wall",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#9d6b52",
    stroke: "#bd9070",
    accent: "#452e22",
    material: "stone",
    brushNote: "Brick coursing — run bricks along a band, quoins at corners",
  },
  {
    id: "terrain:wall-timber",
    name: "Timber Wall",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#84613e",
    stroke: "#97744e",
    accent: "#33241a",
    material: "wood",
    brushNote: "Timber band wall — beam runs with pegged joints",
  },
  {
    id: "terrain:wall-dark",
    name: "Dark Wall",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#5d5f6c",
    stroke: "#868a9a",
    accent: "#26272e",
    material: "stone",
    brushNote: "Cold dark masonry — dungeon and crypt band wall",
  },
  // Levels illusion: stairs (floor-height treads) and roofs (the tallest
  // painted plane — light fascia stroke, hard cast shadow).
  {
    id: "terrain:stairs-stone",
    name: "Stone Stairs",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#6d7280",
    stroke: "#8f95a5",
    accent: "#3f434d",
    material: "stone",
    brushNote: "Step treads — the run infers direction from the strip you paint",
  },
  {
    id: "terrain:roof-shingle",
    name: "Shingle Roof",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#7d7787",
    stroke: "#b7ad92",
    accent: "#565064",
    material: "roof",
    brushNote: "Ridge-lit shingle courses — the tallest square level",
  },
  {
    id: "terrain:roof-thatch",
    name: "Thatch Roof",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#a88c4e",
    stroke: "#c9b67f",
    accent: "#6b592f",
    material: "roof",
    brushNote: "Straw-gold thatch — combed courses over any footprint",
  },
  // Round landmarks (polar-course engine): fills match their VILLAGE_TERRAIN
  // bases (pinned by polarCourse.test) so bake and flat fallback agree.
  {
    id: "terrain:roof-cone",
    name: "Cone Roof",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#6f6a7c",
    stroke: "#b7ad92",
    accent: "#565064",
    material: "roof",
    brushNote: "Round tower cap — paint a blob, get a cone",
  },
  {
    id: "terrain:roof-dome",
    name: "Dome Roof",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#31549b",
    stroke: "#8fa8dc",
    accent: "#22376b",
    material: "roof",
    brushNote: "Blue dome — the longest shadow throw on the map",
  },
  {
    id: "terrain:roof-thatch-spiral",
    name: "Spiral Thatch Roof",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#a28b4e",
    stroke: "#c9b67f",
    accent: "#6f5d34",
    material: "roof",
    brushNote: "Spiral thatch cap — courses wind to the peak",
  },
  {
    id: "terrain:dais-stone",
    name: "Stone Dais",
    category: "terrain",
    layerKind: "terrain",
    columns: 1,
    rows: 1,
    fill: "#8b8f9c",
    stroke: "#b0b4c1",
    accent: "#5c6070",
    material: "stone",
    brushNote: "Round platform — concentric courses from the region centre",
  },
];
